### ISSUE TITLE
Jellyfin Installation on Docker doesn't have "/usr/share/jellyfin/web/index.html" location

### ISSUE THREAD

**Issue by mehmetcanbursalioglu** [n00bcodr/Jellyfin-Enhanced#11]
I got the `System.UnauthorizedAccessException: Access to the path '/jellyfin/jellyfin-web/index.html' is denied.` error and tried the troubleshoot steps but on my system I don't have the `/usr/share/jellyfin` folder .  Only folders with jellyfin-web have locations like this:
`/var/lib/docker/overlay2/1408684cff9445fd3a4beecb23aff5ea5d976720c4b5317f0983c65a876da982/merged/jellyfin/jellyfin-web/67515.9606d372a4e8e0d02e9e.chunk.js`

**Comment by n00bcodr** [comment]
So you'd be copying your index.html from that location, like so.

``` bash
docker cp jellyfin:/jellyfin/jellyfin-web/index.html /path/to/config/index.html
```

**Comment by mehmetcb02** [comment]
OK I did: `docker cp jellyfin:/jellyfin/jellyfin-web/index.html /etc/jellyfin/index.html` and it successfully copied the file then I made these changes on the compose file:

services:
  jellyfin:
    image: jellyfin/jellyfin
    user: 999:987
    network_mode: 'host'
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
    volumes:
      - /etc/jellyfin:/etc/jellyfin
      - /etc/jellyfin/index.html:/jellyfin/jellyfin-web/index.html
      - /var/cache/jellyfin:/var/cache/jellyfin
      - /var/lib/jellyfin:/var/lib/jellyfin
      - /var/log/jellyfin:/var/log/jellyfin
      - /mnt/jellyfin/shows:/mnt/jellyfin/shows
      - /mnt/jellyfin/movies:/mnt/jellyfin/movies

but still the same error after restarting the container.

**Comment by n00bcodr** [comment]
I have released a new version which makes use of  [jellyfin-plugin-file-transformation](https://github.com/IAmParadox27/jellyfin-plugin-file-transformation) to serve the javascript instead of modifying the index.html file. 

This will save a lot of hassle of mounting the index.html for docker installations, please give it a try and let me know how that goes. :)

**Comment by mehmetcb02** [comment]
I have installed file transformation plugin and then uninstalled Jellyfin Enhanced and reinstalled. I still can't get it to work though this time there is no System.UnauthorizedAccessException error on the logs:


jellyfin-jellyfin-1  | [19:08:21] [INF] Jellyfin version: 10.10.7
jellyfin-jellyfin-1  | [19:08:21] [INF] Environment Variables: ["[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]"]
jellyfin-jellyfin-1  | [19:08:21] [INF] Arguments: ["/jellyfin/jellyfin.dll"]
jellyfin-jellyfin-1  | [19:08:21] [INF] Operating system: Debian GNU/Linux 12 (bookworm)
jellyfin-jellyfin-1  | [19:08:21] [INF] Architecture: X64
jellyfin-jellyfin-1  | [19:08:21] [INF] 64-Bit Process: True
jellyfin-jellyfin-1  | [19:08:21] [INF] User Interactive: True
jellyfin-jellyfin-1  | [19:08:21] [INF] Processor count: 2
jellyfin-jellyfin-1  | [19:08:21] [INF] Program data path: /var/lib/jellyfin
jellyfin-jellyfin-1  | [19:08:21] [INF] Log directory path: /var/log/jellyfin
jellyfin-jellyfin-1  | [19:08:21] [INF] Config directory path: /etc/jellyfin
jellyfin-jellyfin-1  | [19:08:21] [INF] Cache path: /var/cache/jellyfin
jellyfin-jellyfin-1  | [19:08:21] [INF] Temp directory path: /tmp/jellyfin
jellyfin-jellyfin-1  | [19:08:21] [INF] Web resources path: /jellyfin/jellyfin-web
jellyfin-jellyfin-1  | [19:08:21] [INF] Application directory: /jellyfin/
jellyfin-jellyfin-1  | [19:08:21] [INF] Marking following migrations as applied because this is a fresh install: ["CreateNetworkConfiguration", "MigrateMusicBrainzTimeout", "MigrateNetworkConfiguration", "MigrateEncodingOptions"]
jellyfin-jellyfin-1  | [19:08:21] [INF] Setting cache path: /var/cache/jellyfin
jellyfin-jellyfin-1  | [19:08:21] [INF] Loading assemblies
jellyfin-jellyfin-1  | [19:08:21] [INF] Loaded assembly Jellyfin.Plugin.FileTransformation, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/File Transformation_2.3.0.0/Jellyfin.Plugin.FileTransformation.dll
jellyfin-jellyfin-1  | [19:08:21] [INF] Loaded assembly IntroSkipper, Version=1.10.10.20, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Intro Skipper_1.10.10.20/IntroSkipper.dll
jellyfin-jellyfin-1  | [19:08:21] [INF] Loaded assembly Jellyfin.Plugin.JellyfinEnhanced, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/JellyfinEnhanced_5.1.0.0/Jellyfin.Plugin.JellyfinEnhanced.dll
jellyfin-jellyfin-1  | [19:08:22] [INF] Loaded assembly Jellyfin.Plugin.TranscodeKiller, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Transcode Killer_3.0.0.0/Jellyfin.Plugin.TranscodeKiller.dll
jellyfin-jellyfin-1  | [19:08:22] [INF] Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
jellyfin-jellyfin-1  | [19:08:22] [INF] Defined LAN exclusions: []
jellyfin-jellyfin-1  | [19:08:22] [INF] Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
jellyfin-jellyfin-1  | [19:08:22] [INF] Filtered interface addresses: ["127.0.0.1", "31.57.77.66", "172.18.0.1", "172.19.0.1"]
jellyfin-jellyfin-1  | [19:08:22] [INF] Bind Addresses ["0.0.0.0"]
jellyfin-jellyfin-1  | [19:08:22] [INF] Remote IP filter is Allowlist
jellyfin-jellyfin-1  | [19:08:22] [INF] Filtered subnets: []
jellyfin-jellyfin-1  | [19:08:27] [INF] Loaded plugin: File Transformation 2.3.0.0
jellyfin-jellyfin-1  | Trailing option(s) found in the command: may be ignored.
jellyfin-jellyfin-1  | Trailing option(s) found in the command: may be ignored.
jellyfin-jellyfin-1  | Trailing option(s) found in the command: may be ignored.
jellyfin-jellyfin-1  | Trailing option(s) found in the command: may be ignored.
jellyfin-jellyfin-1  | [19:08:28] [INF] Loaded plugin: Intro Skipper 1.10.10.20
jellyfin-jellyfin-1  | [19:08:28] [INF] Loaded plugin: Jellyfin Enhanced 5.1.0.0
jellyfin-jellyfin-1  | [19:08:28] [INF] Loaded plugin: Transcode Killer 3.0.0.0
jellyfin-jellyfin-1  | [19:08:28] [INF] Loaded plugin: TMDb 10.10.7.0
jellyfin-jellyfin-1  | [19:08:28] [INF] Loaded plugin: Studio Images 10.10.7.0
jellyfin-jellyfin-1  | [19:08:28] [INF] Loaded plugin: OMDb 10.10.7.0
jellyfin-jellyfin-1  | [19:08:28] [INF] Loaded plugin: MusicBrainz 10.10.7.0
jellyfin-jellyfin-1  | [19:08:28] [INF] Loaded plugin: AudioDB 10.10.7.0
jellyfin-jellyfin-1  | [19:08:28] [INF] Marking following migrations as applied because this is a fresh install: ["DisableTranscodingThrottling", "CreateLoggingConfigHeirarchy", "MigrateActivityLogDatabase", "RemoveDuplicateExtras", "MigrateUserDatabase", "MigrateDisplayPreferencesDatabase", "RemoveDownloadImagesInAdvance", "MigrateAuthenticationDatabase", "FixPlaylistOwner", "MigrateRatingLevels", "FixAudioData", "RemoveDuplicatePlaylistChildren"]
jellyfin-jellyfin-1  | [19:08:28] [WRN] Using an in-memory repository. Keys will not be persisted to storage.
jellyfin-jellyfin-1  | [19:08:28] [WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
jellyfin-jellyfin-1  | [19:08:28] [INF] Kestrel is listening on 0.0.0.0
jellyfin-jellyfin-1  | [19:08:28] [INF] Running startup enqueue
jellyfin-jellyfin-1  | [19:08:28] [INF] Running enqueue of items in library Shows
jellyfin-jellyfin-1  | [19:08:28] [INF] Running enqueue of items in library Movies
jellyfin-jellyfin-1  | [19:08:29] [WRN] No XML encryptor configured. Key {8d0a6429-24eb-46f9-8541-cd0c15dcf994} may be persisted to storage in unencrypted form.
jellyfin-jellyfin-1  | [19:08:29] [WRN] The WebRootPath was not found: /wwwroot. Static files may be unavailable.
jellyfin-jellyfin-1  | [19:08:30] [INF] Running startup tasks
jellyfin-jellyfin-1  | [19:08:30] [INF] Daily trigger for Detect and Analyze Media Segments set to fire at 2025-08-19 00:00:00.000 +00:00, which is 04:51:29.8999776 from now.
jellyfin-jellyfin-1  | [19:08:30] [INF] Daily trigger for Generate Trickplay Images set to fire at 2025-08-19 03:00:00.000 +00:00, which is 07:51:29.8816408 from now.
jellyfin-jellyfin-1  | [19:08:30] [INF] Daily trigger for Extract Chapter Images set to fire at 2025-08-19 02:00:00.000 +00:00, which is 06:51:29.8729218 from now.
jellyfin-jellyfin-1  | [19:08:30] [INF] Found ffmpeg version 7.0.2
jellyfin-jellyfin-1  | [19:08:30] [INF] Available decoders: ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "ac4", "dca", "flac", "mp3", "truehd"]
jellyfin-jellyfin-1  | [19:08:30] [INF] Available encoders: ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_amf", "av1_vaapi", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mjpeg_qsv", "mjpeg_vaapi", "aac", "libfdk_aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
jellyfin-jellyfin-1  | [19:08:30] [INF] Available filters: ["bwdif_cuda", "deinterlace_qsv", "deinterlace_vaapi", "flip_vulkan", "hwupload_cuda", "hwupload_vaapi", "libplacebo", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_vulkan", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "scale_vulkan", "tonemapx", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "transpose_cuda", "transpose_opencl", "transpose_vaapi", "transpose_vulkan", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
jellyfin-jellyfin-1  | [19:08:30] [INF] Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
jellyfin-jellyfin-1  | [19:08:33] [INF] Received transformation registration for 'index.html' with ID 'f69e946a-4b3c-4e9a-8f0a-8d7c1b2c4d9b'
jellyfin-jellyfin-1  | [19:08:33] [INF] Successfully registered Jellyfin Enhanced script injection with the File Transformation plugin.
jellyfin-jellyfin-1  | [19:08:33] [INF] Jellyfin Enhanced Startup Completed after 0 minute(s) and 0 seconds
jellyfin-jellyfin-1  | [19:08:33] [INF] Clean up collections and playlists Completed after 0 minute(s) and 0 seconds
jellyfin-jellyfin-1  | [19:08:33] [INF] Clean Transcode Directory Completed after 0 minute(s) and 0 seconds
jellyfin-jellyfin-1  | [19:08:36] [INF] Watching directory /mnt/jellyfin/shows
jellyfin-jellyfin-1  | [19:08:37] [INF] Update Plugins Completed after 0 minute(s) and 3 seconds
jellyfin-jellyfin-1  | [19:08:40] [INF] Watching directory /mnt/jellyfin/movies
jellyfin-jellyfin-1  | [19:08:59] [INF] FFmpeg: /usr/lib/jellyfin-ffmpeg/ffmpeg
jellyfin-jellyfin-1  | [19:08:59] [INF] ServerId: 1a9b944733644181a435a4f46c8eb74b
jellyfin-jellyfin-1  | [19:08:59] [INF] Core startup complete
jellyfin-jellyfin-1  | [19:08:59] [INF] Startup complete 0:00:38.2040775
jellyfin-jellyfin-1  | [19:10:32] [INF] WS 127.0.0.1 request
jellyfin-jellyfin-1  | [19:12:26] [INF] Saving system configuration
jellyfin-jellyfin-1  | [19:12:26] [INF] Setting cache path: /var/cache/jellyfin
jellyfin-jellyfin-1  | [19:12:26] [INF] Stopping NAT discovery
jellyfin-jellyfin-1  | [19:12:38] [INF] WS 127.0.0.1 closed
jellyfin-jellyfin-1  | [19:12:41] [INF] WS 127.0.0.1 request
jellyfin-jellyfin-1  | [19:13:38] [INF] Saving system configuration
jellyfin-jellyfin-1  | [19:13:38] [INF] Setting cache path: /var/cache/jellyfin
jellyfin-jellyfin-1  | [19:13:43] [INF] WS 127.0.0.1 closed
jellyfin-jellyfin-1  | [19:13:46] [INF] WS 127.0.0.1 request

**Comment by n00bcodr** [comment]
Can you try and force clear your cache please?

**Comment by mehmetcb02** [comment]
Yes it worked!

<img width="1723" height="1080" alt="Image" src="https://github.com/user-attachments/assets/eadcf96f-c7e5-4677-986f-79ec37ffe298" />

**Comment by n00bcodr** [comment]
Perfect!

Glad it worked!
